services:
  claims-validation:
    container_name: data-claims-validation
    profiles:
      - application
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - BUILD_SOURCE=internal
      secrets:
        - github_actor
        - github_token
    ports:
      - "${APP_PORT:-8084}:8081"
      - "${MANAGEMENT_PORT:-8184}:8181"
    environment:
      - FEE_SCHEME_PLATFORM_API_URL=${FEE_SCHEME_PLATFORM_API_URL}
      - FEE_SCHEME_PLATFORM_API_ACCESS_TOKEN=${FEE_SCHEME_PLATFORM_API_ACCESS_TOKEN}
      - PROVIDER_DETAILS_API_URL=${PROVIDER_DETAILS_API_HOSTNAME}
      - PROVIDER_DETAILS_API_ACCESS_TOKEN=${PROVIDER_DETAILS_API_ACCESS_TOKEN}
      - PROVIDER_DETAILS_API_AUTH_HEADER=X-Authorization
      - DATA_CLAIMS_API_URL=http://host.docker.internal:8080
      - DATA_CLAIMS_API_ACCESS_TOKEN=f67f968e-b479-4e61-b66e-f57984931e56
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - SENTRY_DSN=${SENTRY_DSN:-}
      - SENTRY_ENVIRONMENT=${SENTRY_ENVIRONMENT:-local}
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:8181/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
