plugins {
    id 'io.freefair.lombok'
    id 'uk.gov.laa.springboot.laa-spring-boot-gradle-plugin'
    id 'io.sentry.jvm.gradle' version '6.1.0'
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
}

test {
    finalizedBy jacocoTestReport
}

jacocoTestReport {
    afterEvaluate {
        classDirectories.setFrom(files(classDirectories.files.collect {
            fileTree(dir: it, exclude: ['**/ClaimsValidationApplication.class'])
        }))
    }
}

jacocoTestCoverageVerification {
    afterEvaluate {
        classDirectories.setFrom(files(classDirectories.files.collect {
            fileTree(dir: it, exclude: ['**/ClaimsValidationApplication.class'])
        }))
    }
}

dependencies {
    implementation project(':claims-validation-api')
    implementation project(':claims-validation-core')

    implementation 'org.springframework.boot:spring-boot-starter-actuator'
    implementation 'org.springframework.boot:spring-boot-starter-webmvc'
    implementation 'org.springdoc:springdoc-openapi-starter-webmvc-ui:3.0.1'

    implementation 'com.fasterxml.jackson.core:jackson-databind:2.15.4'
    implementation 'uk.gov.justice.laadata.providers:providers-api:1.36.0'

    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testImplementation 'org.springframework.boot:spring-boot-starter-webmvc-test'
    testImplementation 'org.springframework.boot:spring-boot-starter-restclient'
    testImplementation 'org.springframework.boot:spring-boot-test-autoconfigure'

    integrationTestImplementation 'org.springframework.boot:spring-boot-starter-webmvc-test'
    integrationTestImplementation 'org.springframework.boot:spring-boot-test-autoconfigure'

    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'

    developmentOnly 'org.springframework.boot:spring-boot-devtools'
}