plugins {
    id 'org.openapi.generator' version '7.24.0'
    id 'uk.gov.laa.springboot.laa-spring-boot-gradle-plugin'
}

repositories {
    mavenCentral()
}

dependencies {

    /**
     * Upgrades to resolve vulnerabilities
     */
    // Upgrade to fix Uncontrolled Recursion vulnerability in commons-lang3
    implementation 'org.apache.commons:commons-lang3:3.20.0'
    // Upgrade to fix vulnerabilities in tomcat-embed-core
    implementation 'org.apache.tomcat.embed:tomcat-embed-core:11.0.24'
    // Upgrade to fix CVE-2026-1225 vulnerability in logback-core
    implementation 'ch.qos.logback:logback-core:1.6.1'

    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springdoc:springdoc-openapi-starter-webmvc-ui:3.0.3'
}

sourceSets.main.java.srcDirs += ['generated/src/main/java']

checkstyleMain.exclude "*"

openApiGenerate {
    generatorName = "spring"
    inputSpec = "$rootDir/reference-fee-scheme-platform-api/open-api-specification.yml".toString()
    outputDir = "$rootDir/reference-fee-scheme-platform-api/generated".toString()
    apiPackage = "uk.gov.justice.laa.fee.scheme.api"
    invokerPackage = "uk.gov.justice.laa.fee.scheme.invoker"
    modelPackage = "uk.gov.justice.laa.fee.scheme.model"
    configOptions = [
            generateBuilders    : "true",
            interfaceOnly       : "true", // This will only generate interfaces, not implementations
            serializableModel   : "true",
            skipDefaultInterface: "true",
            useJakartaEe        : "true",
            useSpringBoot3      : "true",
            useTags             : "true",
            openApiNullable     : "false"
    ]
}

compileJava.dependsOn 'openApiGenerate'

clean {
    delete "$rootDir/reference-fee-scheme-platform-api/generated"
}

// disable for overall project when running a build
tasks.named('bootJar') {
    enabled = false
}

tasks.named('bootRun') {
    enabled = false
}

tasks.withType(Test).configureEach {
    useJUnitPlatform()
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
}

// publishing configuration: use parent/root version and group
publishing {
    publications {
        mavenJava(MavenPublication) {
            from components.java
            artifactId = project.name
        }
    }
}