plugins {
    id 'java-library'
    id 'maven-publish'
    id 'org.openapi.generator'
    id 'uk.gov.laa.springboot.laa-spring-boot-gradle-plugin'
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            from components.java
            artifactId = 'claims-validation-api'
        }
    }
}

dependencies {
    api 'org.springframework.boot:spring-boot-starter-webmvc'
    api 'org.springdoc:springdoc-openapi-starter-webmvc-ui:3.0.1'
    api 'org.openapitools:jackson-databind-nullable:0.2.8'
}

sourceSets.main.java.srcDirs += ['generated/src/main/java']

checkstyleMain.exclude "*"

openApiGenerate {
    generatorName = "spring"
    inputSpec = "$rootDir/claims-validation-api/open-api-specification.yml".toString()
    outputDir = "$rootDir/claims-validation-api/generated".toString()
    apiPackage = "uk.gov.justice.laa.dstew.payments.claims.api"
    invokerPackage = "uk.gov.justice.laa.dstew.payments.claims.invoker"
    modelPackage = "uk.gov.justice.laa.dstew.payments.claims.model"
    configOptions = [
            generateBuilders    : "true",
            interfaceOnly       : "true", // This will only generate interfaces, not implementations
            serializableModel   : "true",
            skipDefaultInterface: "true",
            useJakartaEe        : "true",
            useSpringBoot3      : "true",
            useTags             : "true",
    ]
}

compileJava.dependsOn 'openApiGenerate'

clean {
    delete "$rootDir/claims-validation-api/generated"
}

// disable for overall project when running a build
tasks.named('bootJar') {
    enabled = false
}

tasks.named('bootRun') {
    enabled = false
}