server:
  port: 8081 # change to desired port number

spring:
  application:
    name: LAA Claims Validation Service
  jackson:
    property-naming-strategy: SNAKE_CASE

management:
  server:
    port: 8181 # change to desired port number
  # specify actuator endpoints to enable
  endpoints:
    web:
      exposure:
        include: health, info, metrics

# LAA API configuration
laa:
  fee-scheme-platform-api:
    url: ${FEE_SCHEME_PLATFORM_API_URL:http://localhost:8082}
    accessToken: ${FEE_SCHEME_PLATFORM_API_ACCESS_TOKEN:}
    authHeader: ${FEE_SCHEME_PLATFORM_API_AUTH_HEADER:Authorization}
    connectTimeoutMs: ${FEE_SCHEME_PLATFORM_API_CONNECT_TIMEOUT:5000}
    readTimeoutMs: ${FEE_SCHEME_PLATFORM_API_READ_TIMEOUT:10000}
  provider-details-api:
    url: ${PROVIDER_DETAILS_API_URL:http://localhost:8083}
    accessToken: ${PROVIDER_DETAILS_API_ACCESS_TOKEN:}
    authHeader: ${PROVIDER_DETAILS_API_AUTH_HEADER:Authorization}
    connectTimeoutMs: ${PROVIDER_DETAILS_API_CONNECT_TIMEOUT:5000}
    readTimeoutMs: ${PROVIDER_DETAILS_API_READ_TIMEOUT:10000}
  data-claims-api:
    url: ${DATA_CLAIMS_API_URL:http://localhost:8084}
    accessToken: ${DATA_CLAIMS_API_ACCESS_TOKEN:}
    authHeader: ${DATA_CLAIMS_API_AUTH_HEADER:Authorization}
    connectTimeoutMs: ${DATA_CLAIMS_API_CONNECT_TIMEOUT:5000}
    readTimeoutMs: ${DATA_CLAIMS_API_READ_TIMEOUT:10000}

sentry:
  dsn: ${SENTRY_DSN:}
  environment: ${SENTRY_ENVIRONMENT:local}

# Logging configuration
logging:
  level:
    uk.gov.justice.laa.dstew.payments.claims: ${LOG_LEVEL:INFO}
    org.springframework.web.reactive.function.client: ${WEBCLIENT_LOG_LEVEL:WARN}
