# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Build Feature

on:
  push:
    branches-ignore:
      - main

env:
  JAVA_VERSION: &JAVA_VERSION '25'
  JDK_DISTRIBUTION: &JDK_DISTRIBUTION 'corretto'

jobs:
  build:
    uses: ministryofjustice/laa-ccms-common-workflows/.github/workflows/gradle-build-and-publish.yml@DSTEW-2417
    permissions:
      contents: write
      packages: write
    with:
      java_version: *JAVA_VERSION
      java_distribution: *JDK_DISTRIBUTION
      integration_test_task: "integrationTest"
      release_type: 'snapshot'
      semgrep_check: 'true'
      junit_results_path: 'claims-validation-core/build/test-results'
      junit_report_path: 'claims-validation-core/build/reports/tests'
      checkstyle_report_path: 'claims-validation-core/build/reports/checkstyle'
      jacoco_coverage_report_path: 'claims-validation-core/build/reports/jacoco'
    secrets:
      gh_token: ${{ secrets.GITHUB_TOKEN }}
      gh_packages_token: ${{ secrets.GH_PACKAGES_TOKEN }}
      aws_region: ${{ vars.LAA_DATA_CLAIMS_EVENT_SERVICE_AWS_REGION }}

  image-scan:
    name: Container image Snyk scan
    uses: ministryofjustice/laa-ccms-common-workflows/.github/workflows/ecr-publish-image.yml@DSTEW-2417
    permissions:
      contents: read
      id-token: write
      security-events: write
    with:
      jar_subproject: 'claims-validation-core'
      image_version: ${{ format('claims-validation-core-snyk-cron-{0}', github.sha) }}
      java_version: *JAVA_VERSION
      java_distribution: *JDK_DISTRIBUTION
      image_scan: 'true'
      publish: 'false'
    secrets:
      gh_token: ${{ secrets.GH_TOKEN }}
      gh_packages_token: ${{ secrets.GH_PACKAGES_TOKEN }}
      ecr_repository: ""
      ecr_region: ""
      ecr_role_to_assume: ""
      snyk_token: ${{ secrets.SNYK_TOKEN }}
