# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Build feature

on:
  push:
    branches-ignore:
      - main

env:
  JAVA_VERSION: &JAVA_VERSION '25'
  JDK_DISTRIBUTION: &JDK_DISTRIBUTION 'corretto'

jobs:
  build:
    uses: ministryofjustice/laa-ccms-common-workflows/.github/workflows/gradle-build-and-publish.yml@dc4173bfc12f714d7e8cbdd9f524d00ef02e25c4 # v2
    permissions:
      contents: write
      packages: write
  
    with:
      java_version: *JAVA_VERSION
      java_distribution: *JDK_DISTRIBUTION
      integration_test_task: "integrationTest"
      publish_package: 'false'
      semgrep_check: 'true'
      junit_results_path: 'claims-validation-core/build/test-results'
      junit_report_path: 'claims-validation-core/build/reports/tests'
      checkstyle_report_path: 'claims-validation-core/build/reports/checkstyle'
      jacoco_coverage_report_path: 'claims-validation-core/build/reports/jacoco'
    secrets:
      # requires a pat due to accessing a private github repos packages (data-claims-api)
      gh_token: ${{ secrets.PHILS_PAT_TOKEN }}
      aws_region: ${{ vars.LAA_DATA_CLAIMS_EVENT_SERVICE_AWS_REGION }}

  sca-scan:
    uses: ./.github/workflows/sca-analysis.yml
    permissions:
      contents: read
      packages: read
      security-events: write
    with:
      java_version: *JAVA_VERSION
      java_distribution: *JDK_DISTRIBUTION
    secrets:
      # requires a pat due to accessing a private github repos packages (data-claims-api)
      gh_token: ${{ secrets.PHILS_PAT_TOKEN }}

  publish-image:
    needs:
      - build
      - sca-scan
    uses: ministryofjustice/laa-ccms-common-workflows/.github/workflows/ecr-publish-image.yml@dc4173bfc12f714d7e8cbdd9f524d00ef02e25c4 # v2
    permissions:
      contents: read
      id-token: write
      security-events: write
    with:
      jar_subproject: 'claims-validation-core'
      image_version: ${{ format('{0}-{1}', vars.LAA_DATA_CLAIMS_EVENT_SERVICE_IMAGE_PREFIX, needs.build.outputs.published_artifact_version) }}
      publish: false
      java_version: *JAVA_VERSION
      java_distribution: *JDK_DISTRIBUTION
    secrets:
      # requires a pat due to accessing a private github repos packages (data-claims-api)
      gh_token: ${{ secrets.PHILS_PAT_TOKEN }} 
      ecr_repository: ""
      ecr_region: ""
      ecr_role_to_assume: ""
      snyk_token: ${{ secrets.SNYK_TOKEN }}
