# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Build Feature

on:
  push:
    branches-ignore:
      - main

env:
  JAVA_VERSION: &JAVA_VERSION '25'
  JDK_DISTRIBUTION: &JDK_DISTRIBUTION 'corretto'

jobs:
  build:
    uses: ministryofjustice/laa-ccms-common-workflows/.github/workflows/gradle-build-and-publish.yml@a5b870c152d0bc4a7f67a23f2c226868f94d7041 # v2.2.2
    permissions:
      contents: write
      packages: write
    with:
      java_version: *JAVA_VERSION
      java_distribution: *JDK_DISTRIBUTION
      integration_test_task: "integrationTest"
      publish_package: 'false'
      semgrep_check: 'true'
      junit_results_path: 'claims-validation-core/build/test-results'
      junit_report_path: 'claims-validation-core/build/reports/tests'
      checkstyle_report_path: 'claims-validation-core/build/reports/checkstyle'
      jacoco_coverage_report_path: 'claims-validation-core/build/reports/jacoco'
    secrets:
      gh_token: ${{ secrets.GITHUB_TOKEN }}
      aws_region: ${{ vars.LAA_DATA_CLAIMS_EVENT_SERVICE_AWS_REGION }}

  sca-scan:
    needs:
      - build
    uses: ./.github/workflows/sca-analysis.yml
    permissions:
      contents: read
      packages: read
      security-events: write
    with:
      java_version: *JAVA_VERSION
      java_distribution: *JDK_DISTRIBUTION
    secrets:
      gh_token: ${{ secrets.GITHUB_TOKEN }}
