# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Build & Publish Main

on:
  push:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      release_type:
        type: choice
        default: "auto"
        options: [ "auto", "none", "patch", "minor", "major" ]

env:
  JAVA_VERSION: &JAVA_VERSION '25'
  JDK_DISTRIBUTION: &JDK_DISTRIBUTION 'corretto'

jobs:
  release:
    uses: ministryofjustice/laa-ccms-common-workflows/.github/workflows/gradle-build-and-publish.yml@main
    permissions:
      contents: write
      packages: write
    with:
      java_version: *JAVA_VERSION
      java_distribution: *JDK_DISTRIBUTION
      release_type: ${{ inputs.release_type != 'auto' && inputs.release_type || '' }}
    secrets:
      gh_token: ${{ secrets.GITHUB_TOKEN }}