name: SCA - Software Composition Analysis

on:
  workflow_call:
    inputs:
      java_version:
        required: false
        type: string
        default: '21'
      java_distribution:
        required:  false
        type: string
        default: 'corretto'
    secrets:
      gh_token:
        required: true
  workflow_dispatch:
    inputs:
      java_version:
        description: 'Java version to use'
        required: false
        default: '21'
      java_distribution:
        description: 'JDK distribution (temurin, corretto, etc.)'
        required: false
        default: 'corretto'

jobs:
  sca:
    name: Software Composition Analysis
    runs-on: ubuntu-latest

    permissions:
      contents: read
      security-events: write

    steps:
      - name: Checkout code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
            fetch-depth: 0

      - name: Set up JDK ${{ inputs.java_version }}
        uses: actions/setup-java@ad2b38190b15e4d6bdf0c97fb4fca8412226d287 # v5
        with:
          java-version: ${{ inputs.java_version }}
          distribution: ${{ inputs.java_distribution }}

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@3f131e8634966bd73d06cc69884922b02e6faf92 # v6.2.0

      - name: Build app jar with gradle
        run: ./gradlew assemble -x test --no-daemon
        env:
          GITHUB_TOKEN: ${{ secrets.gh_token }}

      - name: Run SCA
        uses: ministryofjustice/devsecops-actions/sca@7dc13c20e2bf541b8a77fa1320a04983b18846f6 # v1.6.0
        with:
          token: ${{ secrets.gh_token }}
          renovate: "false"